apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      run: backend
  replicas: 5
  template:
    metadata:
      labels:
        run: backend
        app: backend
    spec:
      containers:
        - name: backend
          image: finleygn/backend:latest
          env:
            - name: PORT
              value: "8000"
            - name: IDENTIFIER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            -  containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      run: gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway
        app: gateway
    spec:
      containers:
        - name: gateway
          image: finleygn/gateway:latest
          env:
            - name: PORT
              value: '8000'
            - name: BACKEND_URL
              value: http://backend.default:9001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            -  containerPort: 8000