apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector: 
    app: backend
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector: 
    app: gateway
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 8000